# =========================================================================
# 2026 FIFA WORLD CUP - MASTER GROUP STAGE STREAM MONITOR CONFIGURATION
# Matches Remaining: 48 Group Stage Matches Left
# Time Zone: UTC (Coordinated Universal Time)
# =========================================================================

# 1. UNIVERSAL SEARCH MATRIX
UNIVERSAL_KEYWORDS = [
    "world cup",
    "World Cup",
    "WORLD CUP",
    "worldcup",
    "WorldCup",
    "fifa world cup",
    "FIFA World Cup",
    "FIFA",
    "fifa",
    "Mundial",
    "mundial",
    "live stream",
    "Live Stream",
    "LIVESTREAM",
    "livestream",
    "live",
    "LIVE"
]

# 2. MASTER FLUID MATCH ENGINE SCHEDULE ARRAY
MATCHES_SCHEDULE = [
    {
        "date": "2026-06-18",
        "matchday": "Matchday 2",
        "group": "Group A",
        "mode": "czech_republic_vs_south_africa",
        "team_1": "Czech Republic",
        "team_2": "South Africa",
        "kickoff_utc_iso": "2026-06-18T16:00:00Z",
        "keywords": [
            "Czech Republic vs South Africa",
            "Czech Republic v South Africa",
            "Czech Republic vs South Africa",
            "czech republic vs south africa",
            "czech republic v south africa",
            "CZECH REPUBLIC VS SOUTH AFRICA",
            "CZECH REPUBLIC V SOUTH AFRICA",
            "CzechRepublicVsSouthAfrica",
            "czechrepublicvssouthafrica",
            "Czech Republic",
            "South Africa",
            "czech republic",
            "south africa",
            "CZECH REPUBLIC",
            "SOUTH AFRICA",
            "CZERSA",
            "czersa",
            "CZE vs RSA",
            "CZEvRSA"
        ]
    },
    {
        "date": "2026-06-18",
        "matchday": "Matchday 2",
        "group": "Group B",
        "mode": "switzerland_vs_bosnia__and_herzegovina",
        "team_1": "Switzerland",
        "team_2": "Bosnia & Herzegovina",
        "kickoff_utc_iso": "2026-06-18T20:00:00Z",
        "keywords": [
            "Switzerland vs Bosnia & Herzegovina",
            "Switzerland v Bosnia & Herzegovina",
            "Switzerland vs Bosnia",
            "switzerland vs bosnia & herzegovina",
            "switzerland v bosnia & herzegovina",
            "SWITZERLAND VS BOSNIA & HERZEGOVINA",
            "SWITZERLAND V BOSNIA & HERZEGOVINA",
            "SwitzerlandVsBosnia&Herzegovina",
            "switzerlandvsbosnia&herzegovina",
            "Switzerland",
            "Bosnia & Herzegovina",
            "switzerland",
            "bosnia & herzegovina",
            "SWITZERLAND",
            "BOSNIA & HERZEGOVINA",
            "Bosnia",
            "bosnia",
            "BOSNIA",
            "SUIBIH",
            "suibih",
            "SUI vs BIH",
            "SUIvBIH"
        ]
    },
    {
        "date": "2026-06-18",
        "matchday": "Matchday 2",
        "group": "Group B",
        "mode": "canada_vs_qatar",
        "team_1": "Canada",
        "team_2": "Qatar",
        "kickoff_utc_iso": "2026-06-18T22:00:00Z",
        "keywords": [
            "Canada vs Qatar",
            "Canada v Qatar",
            "Canada vs Qatar",
            "canada vs qatar",
            "canada v qatar",
            "CANADA VS QATAR",
            "CANADA V QATAR",
            "CanadaVsQatar",
            "canadavsqatar",
            "Canada",
            "Qatar",
            "canada",
            "qatar",
            "CANADA",
            "QATAR",
            "CANQAT",
            "canqat",
            "CAN vs QAT",
            "CANvQAT"
        ]
    },
    {
        "date": "2026-06-18",
        "matchday": "Matchday 2",
        "group": "Group A",
        "mode": "mexico_vs_south_korea",
        "team_1": "Mexico",
        "team_2": "South Korea",
        "kickoff_utc_iso": "2026-06-19T01:00:00Z",
        "keywords": [
            "Mexico vs South Korea",
            "Mexico v South Korea",
            "Mexico vs South Korea",
            "mexico vs south korea",
            "mexico v south korea",
            "MEXICO VS SOUTH KOREA",
            "MEXICO V SOUTH KOREA",
            "MexicoVsSouthKorea",
            "mexicovssouthkorea",
            "Mexico",
            "South Korea",
            "mexico",
            "south korea",
            "MEXICO",
            "SOUTH KOREA",
            "Korea",
            "korea",
            "KOREA",
            "MEXKOR",
            "mexkor",
            "MEX vs KOR",
            "MEXvKOR"
        ]
    },
    {
        "date": "2026-06-19",
        "matchday": "Matchday 2",
        "group": "Group D",
        "mode": "usa_vs_australia",
        "team_1": "USA",
        "team_2": "Australia",
        "kickoff_utc_iso": "2026-06-19T19:00:00Z",
        "keywords": [
            "USA vs Australia",
            "USA v Australia",
            "USA vs Australia",
            "usa vs australia",
            "usa v australia",
            "USA VS AUSTRALIA",
            "USA V AUSTRALIA",
            "USAVsAustralia",
            "usavsaustralia",
            "USA",
            "Australia",
            "usa",
            "australia",
            "USA",
            "AUSTRALIA",
            "USAAUS",
            "usaaus",
            "USA vs AUS",
            "USAvAUS"
        ]
    },
    {
        "date": "2026-06-19",
        "matchday": "Matchday 2",
        "group": "Group C",
        "mode": "scotland_vs_morocco",
        "team_1": "Scotland",
        "team_2": "Morocco",
        "kickoff_utc_iso": "2026-06-19T22:00:00Z",
        "keywords": [
            "Scotland vs Morocco",
            "Scotland v Morocco",
            "Scotland vs Morocco",
            "scotland vs morocco",
            "scotland v morocco",
            "SCOTLAND VS MOROCCO",
            "SCOTLAND V MOROCCO",
            "ScotlandVsMorocco",
            "scotlandvsmorocco",
            "Scotland",
            "Morocco",
            "scotland",
            "morocco",
            "SCOTLAND",
            "MOROCCO",
            "MARMAR",
            "marmar",
            "MAR vs MAR",
            "MARvMAR"
        ]
    },
    {
        "date": "2026-06-19",
        "matchday": "Matchday 2",
        "group": "Group C",
        "mode": "brazil_vs_haiti",
        "team_1": "Brazil",
        "team_2": "Haiti",
        "kickoff_utc_iso": "2026-06-20T00:30:00Z",
        "keywords": [
            "Brazil vs Haiti",
            "Brazil v Haiti",
            "Brazil vs Haiti",
            "brazil vs haiti",
            "brazil v haiti",
            "BRAZIL VS HAITI",
            "BRAZIL V HAITI",
            "BrazilVsHaiti",
            "brazilvshaiti",
            "Brazil",
            "Haiti",
            "brazil",
            "haiti",
            "BRAZIL",
            "HAITI",
            "BRAHAI",
            "brahai",
            "BRA vs HAI",
            "BRAvHAI"
        ]
    },
    {
        "date": "2026-06-20",
        "matchday": "Matchday 2",
        "group": "Group D",
        "mode": "turkey_vs_paraguay",
        "team_1": "Turkey",
        "team_2": "Paraguay",
        "kickoff_utc_iso": "2026-06-20T04:00:00Z",
        "keywords": [
            "Turkey vs Paraguay",
            "Turkey v Paraguay",
            "Turkey vs Paraguay",
            "turkey vs paraguay",
            "turkey v paraguay",
            "TURKEY VS PARAGUAY",
            "TURKEY V PARAGUAY",
            "TurkeyVsParaguay",
            "turkeyvsparaguay",
            "Turkey",
            "Paraguay",
            "turkey",
            "paraguay",
            "TURKEY",
            "PARAGUAY",
            "Türkiye",
            "türkiye",
            "TÜRKIYE",
            "TURPAR",
            "turpar",
            "TUR vs PAR",
            "TURvPAR"
        ]
    },
    {
        "date": "2026-06-20",
        "matchday": "Matchday 2",
        "group": "Group F",
        "mode": "netherlands_vs_sweden",
        "team_1": "Netherlands",
        "team_2": "Sweden",
        "kickoff_utc_iso": "2026-06-20T17:00:00Z",
        "keywords": [
            "Netherlands vs Sweden",
            "Netherlands v Sweden",
            "Netherlands vs Sweden",
            "netherlands vs sweden",
            "netherlands v sweden",
            "NETHERLANDS VS SWEDEN",
            "NETHERLANDS V SWEDEN",
            "NetherlandsVsSweden",
            "netherlandsvssweden",
            "Netherlands",
            "Sweden",
            "netherlands",
            "sweden",
            "NETHERLANDS",
            "SWEDEN",
            "NEDSWE",
            "nedswe",
            "NED vs SWE",
            "NEDvSWE"
        ]
    },
    {
        "date": "2026-06-20",
        "matchday": "Matchday 2",
        "group": "Group E",
        "mode": "germany_vs_ivory_coast",
        "team_1": "Germany",
        "team_2": "Ivory Coast",
        "kickoff_utc_iso": "2026-06-20T20:00:00Z",
        "keywords": [
            "Germany vs Ivory Coast",
            "Germany v Ivory Coast",
            "Germany vs Ivory Coast",
            "germany vs ivory coast",
            "germany v ivory coast",
            "GERMANY VS IVORY COAST",
            "GERMANY V IVORY COAST",
            "GermanyVsIvoryCoast",
            "germanyvsivorycoast",
            "Germany",
            "Ivory Coast",
            "germany",
            "ivory coast",
            "GERMANY",
            "IVORY COAST",
            "Cote d'Ivoire",
            "cote d'ivoire",
            "COTE D'IVOIRE",
            "GERCIV",
            "gerciv",
            "GER vs CIV",
            "GERvCIV"
        ]
    },
    {
        "date": "2026-06-20",
        "matchday": "Matchday 2",
        "group": "Group E",
        "mode": "ecuador_vs_curacao",
        "team_1": "Ecuador",
        "team_2": "Curacao",
        "kickoff_utc_iso": "2026-06-21T01:00:00Z",
        "keywords": [
            "Ecuador vs Curacao",
            "Ecuador v Curacao",
            "Ecuador vs Curacao",
            "ecuador vs curacao",
            "ecuador v curacao",
            "ECUADOR VS CURACAO",
            "ECUADOR V CURACAO",
            "EcuadorVsCuracao",
            "ecuadorvscuracao",
            "Ecuador",
            "Curacao",
            "ecuador",
            "curacao",
            "ECUADOR",
            "CURACAO",
            "Curaçao",
            "curaçao",
            "CURAÇAO",
            "ECUCUW",
            "ecucuw",
            "ECU vs CUW",
            "ECUvCUW"
        ]
    },
    {
        "date": "2026-06-21",
        "matchday": "Matchday 2",
        "group": "Group F",
        "mode": "tunisia_vs_japan",
        "team_1": "Tunisia",
        "team_2": "Japan",
        "kickoff_utc_iso": "2026-06-21T04:00:00Z",
        "keywords": [
            "Tunisia vs Japan",
            "Tunisia v Japan",
            "Tunisia vs Japan",
            "tunisia vs japan",
            "tunisia v japan",
            "TUNISIA VS JAPAN",
            "TUNISIA V JAPAN",
            "TunisiaVsJapan",
            "tunisiavsjapan",
            "Tunisia",
            "Japan",
            "tunisia",
            "japan",
            "TUNISIA",
            "JAPAN",
            "TUNJPN",
            "tunjpn",
            "TUN vs JPN",
            "TUNvJPN"
        ]
    },
    {
        "date": "2026-06-21",
        "matchday": "Matchday 2",
        "group": "Group H",
        "mode": "spain_vs_saudi_arabia",
        "team_1": "Spain",
        "team_2": "Saudi Arabia",
        "kickoff_utc_iso": "2026-06-21T16:00:00Z",
        "keywords": [
            "Spain vs Saudi Arabia",
            "Spain v Saudi Arabia",
            "Spain vs Saudi Arabia",
            "spain vs saudi arabia",
            "spain v saudi arabia",
            "SPAIN VS SAUDI ARABIA",
            "SPAIN V SAUDI ARABIA",
            "SpainVsSaudiArabia",
            "spainvssaudiarabia",
            "Spain",
            "Saudi Arabia",
            "spain",
            "saudi arabia",
            "SPAIN",
            "SAUDI ARABIA",
            "ESPKSA",
            "espksa",
            "ESP vs KSA",
            "ESPvKSA"
        ]
    },
    {
        "date": "2026-06-21",
        "matchday": "Matchday 2",
        "group": "Group G",
        "mode": "belgium_vs_iran",
        "team_1": "Belgium",
        "team_2": "Iran",
        "kickoff_utc_iso": "2026-06-21T19:00:00Z",
        "keywords": [
            "Belgium vs Iran",
            "Belgium v Iran",
            "Belgium vs Iran",
            "belgium vs iran",
            "belgium v iran",
            "BELGIUM VS IRAN",
            "BELGIUM V IRAN",
            "BelgiumVsIran",
            "belgiumvsiran",
            "Belgium",
            "Iran",
            "belgium",
            "iran",
            "BELGIUM",
            "IRAN",
            "BELIRN",
            "belirn",
            "BEL vs IRN",
            "BELvIRN"
        ]
    },
    {
        "date": "2026-06-21",
        "matchday": "Matchday 2",
        "group": "Group H",
        "mode": "uruguay_vs_cape_verde",
        "team_1": "Uruguay",
        "team_2": "Cape Verde",
        "kickoff_utc_iso": "2026-06-21T22:00:00Z",
        "keywords": [
            "Uruguay vs Cape Verde",
            "Uruguay v Cape Verde",
            "Uruguay vs Cape Verde",
            "uruguay vs cape verde",
            "uruguay v cape verde",
            "URUGUAY VS CAPE VERDE",
            "URUGUAY V CAPE VERDE",
            "UruguayVsCapeVerde",
            "uruguayvscapeverde",
            "Uruguay",
            "Cape Verde",
            "uruguay",
            "cape verde",
            "URUGUAY",
            "CAPE VERDE",
            "Cabo Verde",
            "cabo verde",
            "CABO VERDE",
            "URUCPV",
            "urucpv",
            "URU vs CPV",
            "URUvCPV"
        ]
    },
    {
        "date": "2026-06-21",
        "matchday": "Matchday 2",
        "group": "Group G",
        "mode": "new_zealand_vs_egypt",
        "team_1": "New Zealand",
        "team_2": "Egypt",
        "kickoff_utc_iso": "2026-06-22T01:00:00Z",
        "keywords": [
            "New Zealand vs Egypt",
            "New Zealand v Egypt",
            "New Zealand vs Egypt",
            "new zealand vs egypt",
            "new zealand v egypt",
            "NEW ZEALAND VS EGYPT",
            "NEW ZEALAND V EGYPT",
            "NewZealandVsEgypt",
            "newzealandvsegypt",
            "New Zealand",
            "Egypt",
            "new zealand",
            "egypt",
            "NEW ZEALAND",
            "EGYPT",
            "NZLEGY",
            "nzlegy",
            "NZL vs EGY",
            "NZLvEGY"
        ]
    },
    {
        "date": "2026-06-22",
        "matchday": "Matchday 2",
        "group": "Group J",
        "mode": "argentina_vs_austria",
        "team_1": "Argentina",
        "team_2": "Austria",
        "kickoff_utc_iso": "2026-06-22T17:00:00Z",
        "keywords": [
            "Argentina vs Austria",
            "Argentina v Austria",
            "Argentina vs Austria",
            "argentina vs austria",
            "argentina v austria",
            "ARGENTINA VS AUSTRIA",
            "ARGENTINA V AUSTRIA",
            "ArgentinaVsAustria",
            "argentinavsaustria",
            "Argentina",
            "Austria",
            "argentina",
            "austria",
            "ARGENTINA",
            "AUSTRIA",
            "ARGAUT",
            "argaut",
            "ARG vs AUT",
            "ARGvAUT"
        ]
    },
    {
        "date": "2026-06-22",
        "matchday": "Matchday 2",
        "group": "Group I",
        "mode": "france_vs_iraq",
        "team_1": "France",
        "team_2": "Iraq",
        "kickoff_utc_iso": "2026-06-22T21:00:00Z",
        "keywords": [
            "France vs Iraq",
            "France v Iraq",
            "France vs Iraq",
            "france vs iraq",
            "france v iraq",
            "FRANCE VS IRAQ",
            "FRANCE V IRAQ",
            "FranceVsIraq",
            "francevsiraq",
            "France",
            "Iraq",
            "france",
            "iraq",
            "FRANCE",
            "IRAQ",
            "FRAIRQ",
            "frairq",
            "FRA vs IRQ",
            "FRAvIRQ"
        ]
    },
    {
        "date": "2026-06-22",
        "matchday": "Matchday 2",
        "group": "Group I",
        "mode": "norway_vs_senegal",
        "team_1": "Norway",
        "team_2": "Senegal",
        "kickoff_utc_iso": "2026-06-23T00:00:00Z",
        "keywords": [
            "Norway vs Senegal",
            "Norway v Senegal",
            "Norway vs Senegal",
            "norway vs senegal",
            "norway v senegal",
            "NORWAY VS SENEGAL",
            "NORWAY V SENEGAL",
            "NorwayVsSenegal",
            "norwayvssenegal",
            "Norway",
            "Senegal",
            "norway",
            "senegal",
            "NORWAY",
            "SENEGAL",
            "NORSEN",
            "norsen",
            "NOR vs SEN",
            "NORvSEN"
        ]
    },
    {
        "date": "2026-06-23",
        "matchday": "Matchday 2",
        "group": "Group J",
        "mode": "jordan_vs_algeria",
        "team_1": "Jordan",
        "team_2": "Algeria",
        "kickoff_utc_iso": "2026-06-23T03:00:00Z",
        "keywords": [
            "Jordan vs Algeria",
            "Jordan v Algeria",
            "Jordan vs Algeria",
            "jordan vs algeria",
            "jordan v algeria",
            "JORDAN VS ALGERIA",
            "JORDAN V ALGERIA",
            "JordanVsAlgeria",
            "jordanvsalgeria",
            "Jordan",
            "Algeria",
            "jordan",
            "algeria",
            "JORDAN",
            "ALGERIA",
            "JORALG",
            "joralg",
            "JOR vs ALG",
            "JORvALG"
        ]
    },
    {
        "date": "2026-06-23",
        "matchday": "Matchday 2",
        "group": "Group K",
        "mode": "portugal_vs_uzbekistan",
        "team_1": "Portugal",
        "team_2": "Uzbekistan",
        "kickoff_utc_iso": "2026-06-23T17:00:00Z",
        "keywords": [
            "Portugal vs Uzbekistan",
            "Portugal v Uzbekistan",
            "Portugal vs Uzbekistan",
            "portugal vs uzbekistan",
            "portugal v uzbekistan",
            "PORTUGAL VS UZBEKISTAN",
            "PORTUGAL V UZBEKISTAN",
            "PortugalVsUzbekistan",
            "portugalvsuzbekistan",
            "Portugal",
            "Uzbekistan",
            "portugal",
            "uzbekistan",
            "PORTUGAL",
            "UZBEKISTAN",
            "PORUZB",
            "poruzb",
            "POR vs UZB",
            "PORvUZB"
        ]
    },
    {
        "date": "2026-06-23",
        "matchday": "Matchday 2",
        "group": "Group L",
        "mode": "england_vs_ghana",
        "team_1": "England",
        "team_2": "Ghana",
        "kickoff_utc_iso": "2026-06-23T20:00:00Z",
        "keywords": [
            "England vs Ghana",
            "England v Ghana",
            "England vs Ghana",
            "england vs ghana",
            "england v ghana",
            "ENGLAND VS GHANA",
            "ENGLAND V GHANA",
            "EnglandVsGhana",
            "englandvsghana",
            "England",
            "Ghana",
            "england",
            "ghana",
            "ENGLAND",
            "GHANA",
            "ENGGHA",
            "enggha",
            "ENG vs GHA",
            "ENGvGHA"
        ]
    },
    {
        "date": "2026-06-24",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group L",
        "mode": "panama_vs_croatia",
        "team_1": "Panama",
        "team_2": "Croatia",
        "kickoff_utc_iso": "2026-06-23T23:00:00Z",
        "keywords": [
            "Panama vs Croatia",
            "Panama v Croatia",
            "Panama vs Croatia",
            "panama vs croatia",
            "panama v croatia",
            "PANAMA VS CROATIA",
            "PANAMA V CROATIA",
            "PanamaVsCroatia",
            "panamavscroatia",
            "Panama",
            "Croatia",
            "panama",
            "croatia",
            "PANAMA",
            "CROATIA",
            "PANCRO",
            "pancro",
            "PAN vs CRO",
            "PANvCRO"
        ]
    },
    {
        "date": "2026-06-24",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group K",
        "mode": "colombia_vs_dr_congo",
        "team_1": "Colombia",
        "team_2": "DR Congo",
        "kickoff_utc_iso": "2026-06-24T02:00:00Z",
        "keywords": [
            "Colombia vs DR Congo",
            "Colombia v DR Congo",
            "Colombia vs DR Congo",
            "colombia vs dr congo",
            "colombia v dr congo",
            "COLOMBIA VS DR CONGO",
            "COLOMBIA V DR CONGO",
            "ColombiaVsDRCongo",
            "colombiavsdrcongo",
            "Colombia",
            "DR Congo",
            "colombia",
            "dr congo",
            "COLOMBIA",
            "DR CONGO",
            "Congo",
            "congo",
            "CONGO",
            "RDC",
            "rdc",
            "COLCOD",
            "colcod",
            "COL vs COD",
            "COLvCOD"
        ]
    },
    {
        "date": "2026-06-24",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group B",
        "mode": "switzerland_vs_canada",
        "team_1": "Switzerland",
        "team_2": "Canada",
        "kickoff_utc_iso": "2026-06-24T19:00:00Z",
        "keywords": [
            "Switzerland vs Canada",
            "Switzerland v Canada",
            "Switzerland vs Canada",
            "switzerland vs canada",
            "switzerland v canada",
            "SWITZERLAND VS CANADA",
            "SWITZERLAND V CANADA",
            "SwitzerlandVsCanada",
            "switzerlandvscanada",
            "Switzerland",
            "Canada",
            "switzerland",
            "canada",
            "SWITZERLAND",
            "CANADA",
            "SUICAN",
            "suican",
            "SUI vs CAN",
            "SUIvCAN"
        ]
    },
    {
        "date": "2026-06-24",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group B",
        "mode": "bosnia__and_herzegovina_vs_qatar",
        "team_1": "Bosnia & Herzegovina",
        "team_2": "Qatar",
        "kickoff_utc_iso": "2026-06-24T19:00:00Z",
        "keywords": [
            "Bosnia & Herzegovina vs Qatar",
            "Bosnia & Herzegovina v Qatar",
            "Bosnia vs Qatar",
            "bosnia & herzegovina vs qatar",
            "bosnia & herzegovina v qatar",
            "BOSNIA & HERZEGOVINA VS QATAR",
            "BOSNIA & HERZEGOVINA V QATAR",
            "Bosnia&HerzegovinaVsQatar",
            "bosnia&herzegovinavsqatar",
            "Bosnia & Herzegovina",
            "Qatar",
            "bosnia & herzegovina",
            "qatar",
            "BOSNIA & HERZEGOVINA",
            "QATAR",
            "Bosnia",
            "bosnia",
            "BOSNIA",
            "BIHQAT",
            "bihqat",
            "BIH vs QAT",
            "BIHvQAT"
        ]
    },
    {
        "date": "2026-06-24",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group C",
        "mode": "morocco_vs_haiti",
        "team_1": "Morocco",
        "team_2": "Haiti",
        "kickoff_utc_iso": "2026-06-24T22:00:00Z",
        "keywords": [
            "Morocco vs Haiti",
            "Morocco v Haiti",
            "Morocco vs Haiti",
            "morocco vs haiti",
            "morocco v haiti",
            "MOROCCO VS HAITI",
            "MOROCCO V HAITI",
            "MoroccoVsHaiti",
            "moroccovshaiti",
            "Morocco",
            "Haiti",
            "morocco",
            "haiti",
            "MOROCCO",
            "HAITI",
            "MARHAI",
            "marhai",
            "MAR vs HAI",
            "MARvHAI"
        ]
    },
    {
        "date": "2026-06-24",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group C",
        "mode": "scotland_vs_brazil",
        "team_1": "Scotland",
        "team_2": "Brazil",
        "kickoff_utc_iso": "2026-06-24T22:00:00Z",
        "keywords": [
            "Scotland vs Brazil",
            "Scotland v Brazil",
            "Scotland vs Brazil",
            "scotland vs brazil",
            "scotland v brazil",
            "SCOTLAND VS BRAZIL",
            "SCOTLAND V BRAZIL",
            "ScotlandVsBrazil",
            "scotlandvsbrazil",
            "Scotland",
            "Brazil",
            "scotland",
            "brazil",
            "SCOTLAND",
            "BRAZIL",
            "MARBRA",
            "marbra",
            "MAR vs BRA",
            "MARvBRA"
        ]
    },
    {
        "date": "2026-06-25",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group A",
        "mode": "south_africa_vs_south_korea",
        "team_1": "South Africa",
        "team_2": "South Korea",
        "kickoff_utc_iso": "2026-06-25T01:00:00Z",
        "keywords": [
            "South Africa vs South Korea",
            "South Africa v South Korea",
            "South Africa vs South Korea",
            "south africa vs south korea",
            "south africa v south korea",
            "SOUTH AFRICA VS SOUTH KOREA",
            "SOUTH AFRICA V SOUTH KOREA",
            "SouthAfricaVsSouthKorea",
            "southafricavssouthkorea",
            "South Africa",
            "South Korea",
            "south africa",
            "south korea",
            "SOUTH AFRICA",
            "SOUTH KOREA",
            "Korea",
            "korea",
            "KOREA",
            "RSAKOR",
            "rsakor",
            "RSA vs KOR",
            "RSAvKOR"
        ]
    },
    {
        "date": "2026-06-25",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group A",
        "mode": "czech_republic_vs_mexico",
        "team_1": "Czech Republic",
        "team_2": "Mexico",
        "kickoff_utc_iso": "2026-06-25T01:00:00Z",
        "keywords": [
            "Czech Republic vs Mexico",
            "Czech Republic v Mexico",
            "Czech Republic vs Mexico",
            "czech republic vs mexico",
            "czech republic v mexico",
            "CZECH REPUBLIC VS MEXICO",
            "CZECH REPUBLIC V MEXICO",
            "CzechRepublicVsMexico",
            "czechrepublicvsmexico",
            "Czech Republic",
            "Mexico",
            "czech republic",
            "mexico",
            "CZECH REPUBLIC",
            "MEXICO",
            "CZEMEX",
            "czemex",
            "CZE vs MEX",
            "CZEvMEX"
        ]
    },
    {
        "date": "2026-06-25",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group E",
        "mode": "curacao_vs_ivory_coast",
        "team_1": "Curacao",
        "team_2": "Ivory Coast",
        "kickoff_utc_iso": "2026-06-25T20:00:00Z",
        "keywords": [
            "Curacao vs Ivory Coast",
            "Curacao v Ivory Coast",
            "Curacao vs Ivory Coast",
            "curacao vs ivory coast",
            "curacao v ivory coast",
            "CURACAO VS IVORY COAST",
            "CURACAO V IVORY COAST",
            "CuracaoVsIvoryCoast",
            "curacaovsivorycoast",
            "Curacao",
            "Ivory Coast",
            "curacao",
            "ivory coast",
            "CURACAO",
            "IVORY COAST",
            "Curaçao",
            "curaçao",
            "CURAÇAO",
            "Cote d'Ivoire",
            "cote d'ivoire",
            "COTE D'IVOIRE",
            "CUWCIV",
            "cuwciv",
            "CUW vs CIV",
            "CUWvCIV"
        ]
    },
    {
        "date": "2026-06-25",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group E",
        "mode": "ecuador_vs_germany",
        "team_1": "Ecuador",
        "team_2": "Germany",
        "kickoff_utc_iso": "2026-06-25T20:00:00Z",
        "keywords": [
            "Ecuador vs Germany",
            "Ecuador v Germany",
            "Ecuador vs Germany",
            "ecuador vs germany",
            "ecuador v germany",
            "ECUADOR VS GERMANY",
            "ECUADOR V GERMANY",
            "EcuadorVsGermany",
            "ecuadorvsgermany",
            "Ecuador",
            "Germany",
            "ecuador",
            "germany",
            "ECUADOR",
            "GERMANY",
            "ECUGER",
            "ecuger",
            "ECU vs GER",
            "ECUvGER"
        ]
    },
    {
        "date": "2026-06-25",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group F",
        "mode": "tunisia_vs_netherlands",
        "team_1": "Tunisia",
        "team_2": "Netherlands",
        "kickoff_utc_iso": "2026-06-25T23:00:00Z",
        "keywords": [
            "Tunisia vs Netherlands",
            "Tunisia v Netherlands",
            "Tunisia vs Netherlands",
            "tunisia vs netherlands",
            "tunisia v netherlands",
            "TUNISIA VS NETHERLANDS",
            "TUNISIA V NETHERLANDS",
            "TunisiaVsNetherlands",
            "tunisiavsnetherlands",
            "Tunisia",
            "Netherlands",
            "tunisia",
            "netherlands",
            "TUNISIA",
            "NETHERLANDS",
            "TUNNED",
            "tunned",
            "TUN vs NED",
            "TUNvNED"
        ]
    },
    {
        "date": "2026-06-25",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group F",
        "mode": "japan_vs_sweden",
        "team_1": "Japan",
        "team_2": "Sweden",
        "kickoff_utc_iso": "2026-06-25T23:00:00Z",
        "keywords": [
            "Japan vs Sweden",
            "Japan v Sweden",
            "Japan vs Sweden",
            "japan vs sweden",
            "japan v sweden",
            "JAPAN VS SWEDEN",
            "JAPAN V SWEDEN",
            "JapanVsSweden",
            "japanvssweden",
            "Japan",
            "Sweden",
            "japan",
            "sweden",
            "JAPAN",
            "SWEDEN",
            "JPNSWE",
            "jpnswe",
            "JPN vs SWE",
            "JPNvSWE"
        ]
    },
    {
        "date": "2026-06-25",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group D",
        "mode": "turkey_vs_usa",
        "team_1": "Turkey",
        "team_2": "USA",
        "kickoff_utc_iso": "2026-06-26T02:00:00Z",
        "keywords": [
            "Turkey vs USA",
            "Turkey v USA",
            "Turkey vs USA",
            "turkey vs usa",
            "turkey v usa",
            "TURKEY VS USA",
            "TURKEY V USA",
            "TurkeyVsUSA",
            "turkeyvsusa",
            "Turkey",
            "USA",
            "turkey",
            "usa",
            "TURKEY",
            "USA",
            "Türkiye",
            "türkiye",
            "TÜRKIYE",
            "TURUSA",
            "turusa",
            "TUR vs USA",
            "TURvUSA"
        ]
    },
    {
        "date": "2026-06-25",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group D",
        "mode": "paraguay_vs_australia",
        "team_1": "Paraguay",
        "team_2": "Australia",
        "kickoff_utc_iso": "2026-06-26T02:00:00Z",
        "keywords": [
            "Paraguay vs Australia",
            "Paraguay v Australia",
            "Paraguay vs Australia",
            "paraguay vs australia",
            "paraguay v australia",
            "PARAGUAY VS AUSTRALIA",
            "PARAGUAY V AUSTRALIA",
            "ParaguayVsAustralia",
            "paraguayvsaustralia",
            "Paraguay",
            "Australia",
            "paraguay",
            "australia",
            "PARAGUAY",
            "AUSTRALIA",
            "PARAUS",
            "paraus",
            "PAR vs AUS",
            "PARvAUS"
        ]
    },
    {
        "date": "2026-06-26",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group I",
        "mode": "norway_vs_france",
        "team_1": "Norway",
        "team_2": "France",
        "kickoff_utc_iso": "2026-06-26T19:00:00Z",
        "keywords": [
            "Norway vs France",
            "Norway v France",
            "Norway vs France",
            "norway vs france",
            "norway v france",
            "NORWAY VS FRANCE",
            "NORWAY V FRANCE",
            "NorwayVsFrance",
            "norwayvsfrance",
            "Norway",
            "France",
            "norway",
            "france",
            "NORWAY",
            "FRANCE",
            "NORFRA",
            "norfra",
            "NOR vs FRA",
            "NORvFRA"
        ]
    },
    {
        "date": "2026-06-26",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group I",
        "mode": "senegal_vs_iraq",
        "team_1": "Senegal",
        "team_2": "Iraq",
        "kickoff_utc_iso": "2026-06-26T19:00:00Z",
        "keywords": [
            "Senegal vs Iraq",
            "Senegal v Iraq",
            "Senegal vs Iraq",
            "senegal vs iraq",
            "senegal v iraq",
            "SENEGAL VS IRAQ",
            "SENEGAL V IRAQ",
            "SenegalVsIraq",
            "senegalvsiraq",
            "Senegal",
            "Iraq",
            "senegal",
            "iraq",
            "SENEGAL",
            "IRAQ",
            "SENIRQ",
            "senirq",
            "SEN vs IRQ",
            "SENvIRQ"
        ]
    },
    {
        "date": "2026-06-26",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group H",
        "mode": "cape_verde_vs_saudi_arabia",
        "team_1": "Cape Verde",
        "team_2": "Saudi Arabia",
        "kickoff_utc_iso": "2026-06-27T00:00:00Z",
        "keywords": [
            "Cape Verde vs Saudi Arabia",
            "Cape Verde v Saudi Arabia",
            "Cape Verde vs Saudi Arabia",
            "cape verde vs saudi arabia",
            "cape verde v saudi arabia",
            "CAPE VERDE VS SAUDI ARABIA",
            "CAPE VERDE V SAUDI ARABIA",
            "CapeVerdeVsSaudiArabia",
            "capeverdevssaudiarabia",
            "Cape Verde",
            "Saudi Arabia",
            "cape verde",
            "saudi arabia",
            "CAPE VERDE",
            "SAUDI ARABIA",
            "Cabo Verde",
            "cabo verde",
            "CABO VERDE",
            "CPVKSA",
            "cpvksa",
            "CPV vs KSA",
            "CPVvKSA"
        ]
    },
    {
        "date": "2026-06-26",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group H",
        "mode": "uruguay_vs_spain",
        "team_1": "Uruguay",
        "team_2": "Spain",
        "kickoff_utc_iso": "2026-06-27T00:00:00Z",
        "keywords": [
            "Uruguay vs Spain",
            "Uruguay v Spain",
            "Uruguay vs Spain",
            "uruguay vs spain",
            "uruguay v spain",
            "URUGUAY VS SPAIN",
            "URUGUAY V SPAIN",
            "UruguayVsSpain",
            "uruguayvsspain",
            "Uruguay",
            "Spain",
            "uruguay",
            "spain",
            "URUGUAY",
            "SPAIN",
            "URUESP",
            "uruesp",
            "URU vs ESP",
            "URVvESP"
        ]
    },
    {
        "date": "2026-06-26",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group G",
        "mode": "new_zealand_vs_belgium",
        "team_1": "New Zealand",
        "team_2": "Belgium",
        "kickoff_utc_iso": "2026-06-27T03:00:00Z",
        "keywords": [
            "New Zealand vs Belgium",
            "New Zealand v Belgium",
            "New Zealand vs Belgium",
            "new zealand vs belgium",
            "new zealand v belgium",
            "NEW ZEALAND VS BELGIUM",
            "NEW ZEALAND V BELGIUM",
            "NewZealandVsBelgium",
            "newzealandvsbelgium",
            "New Zealand",
            "Belgium",
            "new zealand",
            "belgium",
            "NEW ZEALAND",
            "BELGIUM",
            "NZLBEL",
            "nzlbel",
            "NZL vs BEL",
            "NZLvBEL"
        ]
    },
    {
        "date": "2026-06-26",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group G",
        "mode": "egypt_vs_iran",
        "team_1": "Egypt",
        "team_2": "Iran",
        "kickoff_utc_iso": "2026-06-27T03:00:00Z",
        "keywords": [
            "Egypt vs Iran",
            "Egypt v Iran",
            "Egypt vs Iran",
            "egypt vs iran",
            "egypt v iran",
            "EGYPT VS IRAN",
            "EGYPT V IRAN",
            "EgyptVsIran",
            "egyptvsiran",
            "Egypt",
            "Iran",
            "egypt",
            "iran",
            "EGYPT",
            "IRAN",
            "EGYIRN",
            "egyirn",
            "EGY vs IRN",
            "EGYvIRN"
        ]
    },
    {
        "date": "2026-06-27",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group L",
        "mode": "panama_vs_england",
        "team_1": "Panama",
        "team_2": "England",
        "kickoff_utc_iso": "2026-06-27T21:00:00Z",
        "keywords": [
            "Panama vs England",
            "Panama v England",
            "Panama vs England",
            "panama vs england",
            "panama v england",
            "PANAMA VS ENGLAND",
            "PANAMA V ENGLAND",
            "PanamaVsEngland",
            "panamavsengland",
            "Panama",
            "England",
            "panama",
            "england",
            "PANAMA",
            "ENGLAND",
            "PANENG",
            "paneng",
            "PAN vs ENG",
            "PANvENG"
        ]
    },
    {
        "date": "2026-06-27",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group L",
        "mode": "croatia_vs_ghana",
        "team_1": "Croatia",
        "team_2": "Ghana",
        "kickoff_utc_iso": "2026-06-27T21:00:00Z",
        "keywords": [
            "Croatia vs Ghana",
            "Croatia v Ghana",
            "Croatia vs Ghana",
            "croatia vs ghana",
            "croatia v ghana",
            "CROATIA VS GHANA",
            "CROATIA V GHANA",
            "CroatiaVsGhana",
            "croatiavsghana",
            "Croatia",
            "Ghana",
            "croatia",
            "ghana",
            "CROATIA",
            "GHANA",
            "CROGHA",
            "crogha",
            "CRO vs GHA",
            "CROvGHA"
        ]
    },
    {
        "date": "2026-06-27",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group K",
        "mode": "colombia_vs_portugal",
        "team_1": "Colombia",
        "team_2": "Portugal",
        "kickoff_utc_iso": "2026-06-27T23:30:00Z",
        "keywords": [
            "Colombia vs Portugal",
            "Colombia v Portugal",
            "Colombia vs Portugal",
            "colombia vs portugal",
            "colombia v portugal",
            "COLOMBIA VS PORTUGAL",
            "COLOMBIA V PORTUGAL",
            "ColombiaVsPortugal",
            "colombiavsportugal",
            "Colombia",
            "Portugal",
            "colombia",
            "portugal",
            "COLOMBIA",
            "PORTUGAL",
            "COLPOR",
            "colpor",
            "COL vs POR",
            "COLvPOR"
        ]
    },
    {
        "date": "2026-06-27",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group K",
        "mode": "dr_congo_vs_uzbekistan",
        "team_1": "DR Congo",
        "team_2": "Uzbekistan",
        "kickoff_utc_iso": "2026-06-27T23:30:00Z",
        "keywords": [
            "DR Congo vs Uzbekistan",
            "DR Congo v Uzbekistan",
            "DR Congo vs Uzbekistan",
            "dr congo vs uzbekistan",
            "dr congo v uzbekistan",
            "DR CONGO VS UZBEKISTAN",
            "DR CONGO V UZBEKISTAN",
            "DRCongoVsUzbekistan",
            "drcongovsuzbekistan",
            "DR Congo",
            "Uzbekistan",
            "dr congo",
            "uzbekistan",
            "DR CONGO",
            "UZBEKISTAN",
            "Congo",
            "congo",
            "CONGO",
            "RDC",
            "rdc",
            "CODUZB",
            "coduzb",
            "COD vs UZB",
            "CODvUZB"
        ]
    },
    {
        "date": "2026-06-27",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group J",
        "mode": "algeria_vs_austria",
        "team_1": "Algeria",
        "team_2": "Austria",
        "kickoff_utc_iso": "2026-06-28T02:00:00Z",
        "keywords": [
            "Algeria vs Austria",
            "Algeria v Austria",
            "Algeria vs Austria",
            "algeria vs austria",
            "algeria v austria",
            "ALGERIA VS AUSTRIA",
            "ALGERIA V AUSTRIA",
            "AlgeriaVsAustria",
            "algeriavsaustria",
            "Algeria",
            "Austria",
            "algeria",
            "austria",
            "ALGERIA",
            "AUSTRIA",
            "ALGAUT",
            "algaut",
            "ALG vs AUT",
            "ALGvAUT"
        ]
    },
    {
        "date": "2026-06-27",
        "matchday": "Matchday 3 (Simultaneous Final Group Games)",
        "group": "Group J",
        "mode": "jordan_vs_argentina",
        "team_1": "Jordan",
        "team_2": "Argentina",
        "kickoff_utc_iso": "2026-06-28T02:00:00Z",
        "keywords": [
            "Jordan vs Argentina",
            "Jordan v Argentina",
            "Jordan vs Argentina",
            "jordan vs argentina",
            "jordan v argentina",
            "JORDAN VS ARGENTINA",
            "JORDAN V ARGENTINA",
            "JordanVsArgentina",
            "jordanvsargentina",
            "Jordan",
            "Argentina",
            "jordan",
            "argentina",
            "JORDAN",
            "ARGENTINA",
            "JORARG",
            "jorarg",
            "JOR vs ARG",
            "JORvARG"
        ]
    }
]
